name: neuroburst
description: A 2D action-defense game built with Flutter and Flame
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0
  flame_audio: ^2.10.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/shoot.mp3
    - assets/audio/hit.mp3
    - assets/audio/bit_collect.mp3
    - assets/audio/enemy_death.mp3
    - assets/audio/boss_spawn.mp3
    - assets/audio/level_up.mp3
    - assets/audio/game_over.mp3
    - assets/audio/background.mp3
    
  fonts:
    - family: Cyberpunk
      fonts:
        - asset: assets/fonts/Cyberpunk.ttf 